recover from failure in samtools install

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -21,7 +21,7 @@ export PKG_CONFIG_PATH=$LIBDIR/pkgconfig:$PKG_CONFIG_PATH
 echo "Installing TransDecoder" && \
 (cd $BINDIR && tar -xzf TransDecoder-v5.7.1.tar.gz && rm -f  TransDecoder-v5.7.1.tar.gz) && \
 echo "Installing samtools" && \
-(cd $BINDIR && tar -xzf samtools-1.21.tgz && cd samtools-1.21 && ./configure --prefix=$DEST --disable-lzma --without-curses && make -j; make install && cd .. && rm -rf  samtools-1.21.tgz samtools-1.21) && \
+(cd $BINDIR && tar -xzf samtools-1.21.tgz && cd samtools-1.21 && ./configure --prefix=$DEST --disable-lzma --without-curses && make -j; make install || echo "samtools installation failed, please make sure samtoold are available on the system PATH for running EviAnn" && cd .. && rm -rf  samtools-1.21.tgz samtools-1.21) && \
 echo "Installing miniprot" && \
 (cd $BINDIR && tar -xzf miniprot.tgz && cd miniprot_source && make && mv miniprot ../ && cd .. && rm -rf  miniprot_source miniprot.tgz) && \
 echo "Installation successful!" || echo "Installation failed"
