edited install script

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -17,8 +17,9 @@ export NUM_THREADS=`grep -c '^processor' /proc/cpuinfo 2>/dev/null || sysctl -n 
 BINDIR=$DEST/bin
 LIBDIR=$DEST/lib
 export PKG_CONFIG_PATH=$LIBDIR/pkgconfig:$PKG_CONFIG_PATH
-(cd global-1 && ./configure --prefix=$DEST --bindir=$BINDIR --libdir=$LIBDIR && make -j $NUM_THREADS install-special)
-(cd $BINDIR && tar -xzf TransDecoder-v5.7.1.tar.gz && rm -f  TransDecoder-v5.7.1.tar.gz)
-(cd $BINDIR && tar -xvzf snap.tgz && cd SNAP && make && rm -rf ../snap.tgz )
+(cd global-1 && ./configure --prefix=$DEST --bindir=$BINDIR --libdir=$LIBDIR && make -j $NUM_THREADS install-special) && \
+(cd $BINDIR && tar -xzf TransDecoder-v5.7.1.tar.gz && rm -f  TransDecoder-v5.7.1.tar.gz) && \
+(cd $BINDIR && tar -xvzf snap.tgz && cd SNAP && make && rm -rf ../snap.tgz ) && \
+echo "Installation successful!" || echo "Installation failed"
 
 
