modified installer to use static samtools executable

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -26,12 +26,13 @@ export PKG_CONFIG_PATH=$LIBDIR/pkgconfig:$PKG_CONFIG_PATH
 (cd global-1 && ./configure --prefix=$DEST --bindir=$BINDIR --libdir=$LIBDIR && make -j $NUM_THREADS install-special) && \
 echo "Installing TransDecoder" && \
 (cd $BINDIR && tar -xzf TransDecoder-v5.7.1a.tar.gz && rm -f  TransDecoder-v5.7.1a.tar.gz) && \
-echo "Installing samtools" && \
-(cd $BINDIR && tar -xzf samtools-1.15.1.tgz && cd samtools-1.15.1 && ./configure --prefix=$DEST --disable-lzma --without-curses && make -j; make install || echo -e "${RC}[WARNING!!! samtools installation failed, please make sure samtools are available on the system PATH for running EviAnn]${NC}" && cd .. && rm -rf  samtools-1.15.1.tgz samtools-1.15.1) && \
+#echo "Installing samtools" && \
+#(cd $BINDIR && tar -xzf samtools-1.15.1.tgz && cd samtools-1.15.1 && ./configure --prefix=$DEST --disable-lzma --without-curses && make -j; make install || echo -e "${RC}[WARNING!!! samtools installation failed, please make sure samtools are available on the system PATH for running EviAnn]${NC}" && cd .. && rm -rf  samtools-1.15.1.tgz samtools-1.15.1) && \
 echo "Installing miniprot" && \
 (cd $BINDIR && tar -xzf miniprot.tgz && cd miniprot_source && make && mv miniprot ../ && cd .. && rm -rf  miniprot_source miniprot.tgz) && \
 echo "Checking static executables" && \
-if [ $(bin/makeblastdb -h 1>/dev/null 2>&1; echo $?) -gt 0 ];then echo -e "${RC}[WARNING!!! installed makeblastdb, tblastn and blastp executables are not compatible, please make sure they are available on the system PATH for running EviAnn]${NC}" && rm -f bin/{makeblastdb,blastp,tblastn};fi && \
+if [ $(bin/makeblastdb -h 1>/dev/null 2>&1; echo $?) -gt 0 ];then echo -e "${RC}[WARNING!!! installed makeblastdb, tblastn and blastp executables are not compatible, please make sure they are available on the system PATH for running EviAnn]${NC}" && rm -f bin/{makeblastdb,blastp,tblastn};fi
+if [ $(bin/stringtie -h 1>/dev/null 2>&1; echo $?) -gt 0 ];then echo -e "${RC}[WARNING!!! installed stringtie executable is not compatible, please make sure stringtie is available on the system PATH for running EviAnn]${NC}" && rm -f bin/stringtie;fi
+if [ $(bin/samtools --help 1>/dev/null 2>&1; echo $?) -gt 0 ];then echo -e "${RC}[WARNING!!! installed samtools executable is not compatible, please make sure samtools are available on the system PATH for running EviAnn]${NC}" && rm -f bin/samtools;fi
 echo "Installation successful!" || echo "Installation failed"
-
 
